server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # STUDENT SERVICE
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**

        # COURSE SERVICE - Courses
        - id: course-service-courses
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**

        # COURSE SERVICE - Exams
        - id: course-service-exams
          uri: lb://course-service
          predicates:
            - Path=/api/exams/**

        # COURSE SERVICE - Enrollments
        - id: course-service-enrollments
          uri: lb://course-service
          predicates:
            - Path=/api/enrollments/**

        # COURSE SERVICE - Grades
        - id: course-service-grades
          uri: lb://course-service
          predicates:
            - Path=/api/grades/**

      # CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:4200"
              - "file://"
              - "null"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    ma.education.gatewayservice: DEBUG