server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: student-service
            uri: lb://student-service
            predicates:
              - Path=/api/students/**

          - id: course-service-courses
            uri: lb://course-service
            predicates:
              - Path=/api/courses/**

          - id: course-service-exams
            uri: lb://course-service
            predicates:
              - Path=/api/exams/**

          - id: course-service-enrollments
            uri: lb://course-service
            predicates:
              - Path=/api/enrollments/**

          - id: course-service-grades
            uri: lb://course-service
            predicates:
              - Path=/api/grades/**

          - id: portal-service-auth
            uri: lb://portal-service
            predicates:
              - Path=/api/auth/**

          - id: portal-service-portal
            uri: lb://portal-service
            predicates:
              - Path=/api/portal/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway