server:
  port: 8083

spring:
  application:
    name: portal-service
  datasource:
    url: jdbc:mysql://localhost:3306/portal_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Configuration JWT
jwt:
  secret: VotreCleSecreteTresLongueEtSecuriseeDeMinimum256BitsPoURJWT2024PlatformeEducativeMaroc
  expiration: 86400000 # 24 heures en millisecondes

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics